---
- name: Ansible conditionals demo
  hosts: linuxservers
  #sudo privileges
  become: true
  tasks:
    - name: install nginx on Ubuntu
      apt: name=nginx state=latest
      # This will generate an error on CentOS
      ignore_errors: yes
      # When it fails, want to store the failure in a variable
      # for next task to run in case of failure
      register: results

    - name: install nginx on CentOS
      dnf: name=nginx state=latest
      #will run because the apt will not work on CentOS
      when: results|failed